//! CLI implementation for BLS12-381 Aiken

use clap::{Parser, Subcommand};
use std::error::Error;

mod cmd;

/// CLI commands available
#[derive(Debug, Subcommand)]
pub enum Command {
    /// Generate a 32-byte random hex-encoded seed
    ///
    /// This command generates a cryptographically secure random seed
    /// that can be used as input for the hkdf command to derive
    /// a private key. The output is a 64-character hex string
    /// representing 32 bytes of random data.
    ///
    /// Examples:
    ///
    ///   $ bls-aiken generate-seed
    #[command(disable_help_flag = true)]
    GenerateSeed,

    /// Derive a 32-byte PrivateKey from a seed using HKDF-SHA256
    ///
    /// This command takes a seed (typically generated by generate-seed)
    /// and derives a 32-byte private key using the HKDF (HMAC-based Key Derivation Function)
    /// with SHA-256. The output is a 64-character hex string.
    ///
    /// Examples:
    ///
    ///   $ echo "seed_hex" | bls-aiken hkdf
    ///
    ///   $ bls-aiken hkdf --file seed.hex
    ///
    ///   $ bls-aiken hkdf < seed.hex
    #[command(disable_help_flag = true)]
    Hkdf(cmd::hkdf::Args),

    /// Convert a 32-byte private key to its BLS12-381 scalar representation
    ///
    /// This command converts a 32-byte private key (as generated by hkdf)
    /// to its corresponding scalar in the BLS12-381 curve's scalar field.
    /// The output is a decimal representation of the scalar.
    ///
    /// Examples:
    ///
    ///   $ echo "private_key_hex" | bls-aiken scalar
    ///
    ///   $ bls-aiken scalar --prv private_key.hex
    ///
    ///   $ bls-aiken scalar < private_key.hex
    #[command(disable_help_flag = true)]
    Scalar(cmd::scalar::Args),

    /// Generate a BLS12-381 public key (G1 point) from a private key
    ///
    /// This command computes the public key by multiplying the G1 generator
    /// by the scalar derived from the private key. The output is a
    /// 96-character hex string (48 bytes) representing the compressed G1 point.
    ///
    /// Examples:
    ///
    ///   $ echo "private_key_hex" | bls-aiken pk
    ///
    ///   $ bls-aiken pk --prv private_key.hex
    ///
    ///   $ bls-aiken pk < private_key.hex
    #[command(disable_help_flag = true)]
    Pk(cmd::pk::Args),

    /// Generate a BLS signature (G2 point) from a private key and message
    ///
    /// This command generates a BLS signature by hashing the message to G2
    /// and then multiplying by the scalar derived from the private key.
    /// The output is a 192-character hex string (96 bytes) representing the compressed G2 point.
    ///
    /// Examples:
    ///
    ///   $ echo "private_key_hex" | bls-aiken sig --msg "hello"
    ///
    ///   $ bls-aiken sig --prv private_key.hex --msg "hello"
    ///
    ///   $ bls-aiken sig --prv key.hex --msg "test" --dst "domain" --aug "extra"
    #[command(disable_help_flag = true)]
    Sig(cmd::sig::Args),

    /// Verify a BLS signature
    ///
    /// This command verifies a BLS signature by checking the pairing equality:
    /// e(public_key, hash_to_curve(message)) == e(G1_generator, signature)
    ///
    /// Examples:
    ///
    ///   $ echo "signature_hex" | bls-aiken verify --msg "hello" --pk pk.hex
    ///
    ///   $ bls-aiken verify --sig sig.hex --msg "hello" --pk pk.hex
    ///
    ///   $ bls-aiken verify --sig sig.hex --msg "test" --pk key.hex --dst "domain" --aug "extra"
    #[command(disable_help_flag = true)]
    Verify(cmd::verify::Args),

    /// Add two BLS12-381 points (G1 or G2 group)
    ///
    /// This command adds two compressed points in the chosen group.
    /// Both points are decompressed, added, and the result is re-compressed.
    /// The output is a hex string (96 hex chars for G1, 192 hex chars for G2)
    /// representing the compressed result point.
    ///
    /// Examples:
    ///
    ///   $ echo "left_point_hex" | bls-aiken add --g1 --point_right "right_hex"
    ///
    ///   $ bls-aiken add --g2 --point_left left.hex --point_right "right_hex"
    #[command(disable_help_flag = true)]
    Add(cmd::add::Args),

    /// Multiply a BLS12-381 point by a scalar
    ///
    /// This command multiplies a compressed G1 or G2 point by a scalar value.
    /// The point is decompressed, multiplied, and re-compressed.
    /// The output is a hex string (96 hex chars for G1, 192 hex chars for G2)
    /// representing the compressed result point.
    ///
    /// Examples:
    ///
    ///   $ echo "point_hex" | bls-aiken mul --g1 --scalar "00...00"
    ///
    ///   $ bls-aiken mul --g2 --point point.hex --scalar "00...00"
    #[command(disable_help_flag = true)]
    Mul(cmd::mul::Args),

    /// Compress a BLS12-381 point (G1 or G2)
    ///
    /// This command validates and compresses a G1 or G2 point.
    /// Accepts both compressed (48/96 bytes) and uncompressed (96/192 bytes) input.
    /// The output is always the compressed hex form.
    ///
    /// Examples:
    ///
    ///   $ echo "point_hex" | bls-aiken compress --g1
    ///
    ///   $ bls-aiken compress --g2 --point point.hex
    ///
    ///   $ bls-aiken compress --g1 --point identity
    #[command(disable_help_flag = true)]
    Compress(cmd::compress::Args),

    /// Uncompress (decompress) a BLS12-381 point (G1 or G2)
    ///
    /// This command decompresses a compressed G1 or G2 point and outputs
    /// the uncompressed form. For G1 the output is 192 hex chars (96 bytes),
    /// for G2 it is 384 hex chars (192 bytes).
    ///
    /// Examples:
    ///
    ///   $ echo "point_hex" | bls-aiken uncompress --g1
    ///
    ///   $ bls-aiken uncompress --g2 --point point.hex
    ///
    ///   $ bls-aiken uncompress --g1 --point identity
    #[command(disable_help_flag = true)]
    Uncompress(cmd::uncompress::Args),
}

#[derive(Debug, Parser)]
#[clap(name = "bls12-381-aiken-cli")]
#[clap(bin_name = "bls-aiken")]
#[clap(author = "HAL Team <hal@cardanofoundation.org>")]
#[clap(version=env!("CARGO_PKG_VERSION"))]
#[clap(about = "BLS12-381 Aiken CLI tool")]
#[command(disable_help_flag = true)]
pub struct Cli {
    #[arg(short = 'h', long = "help", global = true, action = clap::ArgAction::HelpLong, help = "Print help")]
    help: Option<bool>,
    #[command(subcommand)]
    command: Command,
}

fn main() -> Result<(), Box<dyn Error>> {
    let args = Cli::parse();

    match args.command {
        Command::GenerateSeed => cmd::generate_seed::run(),
        Command::Hkdf(args) => cmd::hkdf::run(args),
        Command::Scalar(args) => cmd::scalar::run(args),
        Command::Pk(args) => cmd::pk::run(args),
        Command::Sig(args) => cmd::sig::run(args),
        Command::Verify(args) => cmd::verify::run(args),
        Command::Add(args) => cmd::add::run(args),
        Command::Mul(args) => cmd::mul::run(args),
        Command::Compress(args) => cmd::compress::run(args),
        Command::Uncompress(args) => cmd::uncompress::run(args),
    }
}
