//! CLI implementation for BLS12-381 Aiken

use clap::{Parser, Subcommand};
use std::error::Error;

mod cmd;

/// CLI commands available
#[derive(Debug, Subcommand)]
pub enum Command {
    /// Generate a 32-byte random hex-encoded seed
    ///
    /// This command generates a cryptographically secure random seed
    /// that can be used as input for the hkdf command to derive
    /// a private key. The output is a 64-character hex string
    /// representing 32 bytes of random data.
    ///
    /// Examples:
    ///   cargo run --quiet -- generate-seed
    ///   cargo run --quiet -- generate-seed ; echo
    GenerateSeed,

    /// Derive a 32-byte PrivateKey from a seed using HKDF-SHA256
    ///
    /// This command takes a seed (typically generated by generate-seed)
    /// and derives a 32-byte private key using the HKDF (HMAC-based Key Derivation Function)
    /// with SHA-256. The output is a 64-character hex string.
    ///
    /// Examples:
    ///   echo "seed_hex" | cargo run -- hkdf
    ///   cargo run -- hkdf --file seed.hex
    ///   cargo run -- hkdf < seed.hex
    Hkdf(cmd::hkdf::Args),

    /// Convert a 32-byte private key to its BLS12-381 scalar representation
    ///
    /// This command converts a 32-byte private key (as generated by hkdf)
    /// to its corresponding scalar in the BLS12-381 curve's scalar field.
    /// The output is a decimal representation of the scalar.
    ///
    /// Examples:
    ///   echo "private_key_hex" | cargo run -- scalar
    ///   cargo run -- scalar --prv private_key.hex
    ///   cargo run -- scalar < private_key.hex
    Scalar(cmd::scalar::Args),

    /// Generate a BLS12-381 public key (G1 point) from a private key
    ///
    /// This command computes the public key by multiplying the G1 generator
    /// by the scalar derived from the private key. The output is a
    /// 96-character hex string (48 bytes) representing the compressed G1 point.
    ///
    /// Examples:
    ///   echo "private_key_hex" | cargo run -- pk
    ///   cargo run -- pk --prv private_key.hex
    ///   cargo run -- pk < private_key.hex
    Pk(cmd::pk::Args),

    /// Generate a BLS signature (G2 point) from a private key and message
    ///
    /// This command generates a BLS signature by hashing the message to G2
    /// and then multiplying by the scalar derived from the private key.
    /// The output is a 192-character hex string (96 bytes) representing the compressed G2 point.
    ///
    /// Parameters:
    ///   --prv: Private key (from stdin or file)
    ///   --msg: Message to sign (required)
    ///   --dst: Domain separation tag (optional, defaults to empty)
    ///   --aug: Augmentation data (optional, defaults to empty)
    ///
    /// Examples:
    ///   echo "private_key_hex" | cargo run -- sig --msg "hello"
    ///   cargo run -- sig --prv private_key.hex --msg "hello"
    ///   cargo run -- sig --prv key.hex --msg "test" --dst "domain" --aug "extra"
    Sig(cmd::sig::Args),
}

#[derive(Debug, Parser)]
#[clap(name = "bls12-381-aiken-cli")]
#[clap(bin_name = "bls-aiken")]
#[clap(author = "HAL Team <hal@cardanofoundation.org>")]
#[clap(version=env!("CARGO_PKG_VERSION"))]
#[clap(about = "BLS12-381 Aiken CLI tool")]
#[clap(about, long_about = None)]
pub struct Cli {
    #[command(subcommand)]
    command: Command,
}

fn main() -> Result<(), Box<dyn Error>> {
    let args = Cli::parse();

    match args.command {
        Command::GenerateSeed => cmd::generate_seed::run(),
        Command::Hkdf(args) => cmd::hkdf::run(args),
        Command::Scalar(args) => cmd::scalar::run(args),
        Command::Pk(args) => cmd::pk::run(args),
        Command::Sig(args) => cmd::sig::run(args),
    }
}
